#!/usr/bin/env python3
# ---
# template: execution
# version: 1.1.0
# summary: "Dumps deterministic snapshots of live infrastructure state to <agent-home>/system-state/ for git-backed backup and drift detection. Captures crontab, Claude Code hooks, public settings (secrets stripped), local MCP servers (via `claude mcp list`), and ~/.bashrc. Layer 2 of the live-infrastructure documentation pattern (Layer 1 = the personal layer's context/indexed/active-systems.md manual overview)."
# created: 2026-04-30
# last_updated: 2026-06-25
# maintainer: the-operator
# ---
"""
dump_system_state.py — Snapshot live infrastructure state to git-backed files.

Pairs with the personal layer's context/indexed/active-systems.md (manual overview, the "why")
to give a complete live-infrastructure picture: this script produces the
"exactly what's currently configured" backups.

Outputs (under <agent-home>/system-state/):

  crontab.txt              — output of `crontab -l`
  claude-hooks.json        — extracted hooks block from ~/.claude/settings.json
  claude-settings-public.json — full settings.json minus any secret-shaped fields
  installed-mcp-servers.txt — local MCP servers from `claude mcp list` (health suffix stripped)
  bashrc.snapshot          — copy of ~/.bashrc (env vars, aliases, functions)
  README.md                — explains what these are and how they're regenerated

Run modes:
  python3 dump_system_state.py          # default — write all dumps
  python3 dump_system_state.py --dry-run # show what would change, write nothing
  python3 dump_system_state.py --quiet   # minimal output

Idempotent: re-running without changes produces no diff. Designed to run from
postflight.sh step 0c on every debrief, with output auto-staged on the agents
commit. Stdlib-only; no API calls, no LLM.
"""

from __future__ import annotations

import argparse
import json
import os
import subprocess
import sys
from pathlib import Path
from typing import Any


SECRET_KEY_PATTERNS = ("token", "key", "secret", "password", "credential", "auth")
HOME = Path(os.path.expanduser("~"))
SETTINGS_PATH = HOME / ".claude" / "settings.json"

# Resolve the agent home rather than naming one: this script is shared, and a
# hardcoded agent directory silently writes one agent's state into another's.
sys.path.insert(0, str(Path(__file__).resolve().parent))
from agent_paths import agent_home  # noqa: E402

OUTPUT_DIR = agent_home() / "system-state"


def redact_secrets(obj: Any, parent_key: str = "") -> Any:
    """Walk a JSON-shaped object and replace likely-secret values with a marker.

    Conservative: any string-valued key whose name contains a secret keyword is
    redacted. Nested dicts and lists are walked recursively. Numbers, booleans,
    and structural elements pass through unchanged.
    """
    if isinstance(obj, dict):
        out = {}
        for k, v in obj.items():
            lower_k = k.lower()
            is_secret_key = any(p in lower_k for p in SECRET_KEY_PATTERNS)
            if is_secret_key and isinstance(v, str) and v:
                out[k] = "<REDACTED>"
            else:
                out[k] = redact_secrets(v, parent_key=k)
        return out
    if isinstance(obj, list):
        return [redact_secrets(item, parent_key=parent_key) for item in obj]
    return obj


def dump_crontab(out_dir: Path, dry_run: bool, quiet: bool) -> None:
    """Capture `crontab -l` output. Empty crontab is allowed (writes a header)."""
    target = out_dir / "crontab.txt"
    try:
        result = subprocess.run(
            ["crontab", "-l"], capture_output=True, text=True, check=False
        )
        # crontab -l returns non-zero if no crontab exists; treat as empty
        body = result.stdout if result.returncode == 0 else ""
    except FileNotFoundError:
        body = "# crontab command not available\n"

    header = (
        "# Snapshot of `crontab -l` — auto-generated by executions/dump_system_state.py\n"
        "# Source of truth: the live crontab. Edit via `crontab -e`.\n"
        "# This file is regenerated at every session-debrief and committed to the agents repo.\n\n"
    )
    content = header + body

    write_if_changed(target, content, dry_run, quiet, label="crontab")


def dump_claude_hooks_and_settings(out_dir: Path, dry_run: bool, quiet: bool) -> None:
    """Extract hooks block and write redacted full settings."""
    if not SETTINGS_PATH.exists():
        if not quiet:
            print(f"WARN: {SETTINGS_PATH} not found, skipping hooks/settings dump", file=sys.stderr)
        return

    try:
        with open(SETTINGS_PATH, "r", encoding="utf-8") as f:
            settings = json.load(f)
    except (OSError, json.JSONDecodeError) as e:
        print(f"ERROR: failed to read/parse {SETTINGS_PATH}: {e}", file=sys.stderr)
        return

    # 1. Hooks-only dump (the load-bearing piece for live-infrastructure docs)
    hooks_block = settings.get("hooks", {})
    hooks_content = json.dumps(hooks_block, indent=2, sort_keys=True) + "\n"
    write_if_changed(out_dir / "claude-hooks.json", hooks_content, dry_run, quiet, label="claude-hooks")

    # 2. Full settings dump with secrets redacted
    redacted = redact_secrets(settings)
    settings_content = json.dumps(redacted, indent=2, sort_keys=True) + "\n"
    write_if_changed(out_dir / "claude-settings-public.json", settings_content, dry_run, quiet, label="claude-settings-public")


def dump_mcp_servers(out_dir: Path, dry_run: bool, quiet: bool) -> None:
    """Capture local MCP servers from the live `claude mcp` registry.

    NOTE: local MCP servers are registered via `claude mcp add`, NOT in
    settings.json's `mcpServers` block (which is typically empty here). The live
    registry is only readable via `claude mcp list`. We strip the volatile
    `- ✔ Connected` / `- ✘ Failed` health suffix so the snapshot is stable and
    only churns on a real config change (add/remove/edit), not transient health.
    claude.ai-hosted connectors (Vercel, Mermaid, Google Workspace, etc.) are
    NOT local servers and do not appear here.
    """
    lines = [
        "# Installed MCP servers — auto-generated by executions/dump_system_state.py",
        "# Source: `claude mcp list` (the live local-server registry; `claude mcp add`",
        "#   stores these OUTSIDE settings.json). Health-status suffix is stripped so",
        "#   this snapshot only changes when the server config changes.",
        "# This file is regenerated at every session-debrief.",
        "",
    ]
    try:
        result = subprocess.run(
            ["claude", "mcp", "list"], capture_output=True, text=True, check=False, timeout=60
        )
        raw = result.stdout
    except (OSError, subprocess.SubprocessError):
        raw = ""

    # Keep only "name: command" lines; drop the "Checking…" header and blanks,
    # and strip the trailing " - <status>" health marker.
    entries = []
    for line in raw.splitlines():
        line = line.rstrip()
        if not line or ":" not in line or line.startswith("#"):
            continue
        # health suffix is " - ✔ Connected" / " - ✘ Failed to connect" etc.
        for sep in (" - ✔", " - ✘", " - ✓", " - ✗"):
            idx = line.find(sep)
            if idx != -1:
                line = line[:idx].rstrip()
                break
        entries.append(f"- {line}")

    if entries:
        lines.extend(sorted(entries))
    else:
        lines.append("# `claude mcp list` returned no servers (or CLI unavailable in this shell).")

    content = "\n".join(lines) + "\n"
    write_if_changed(out_dir / "installed-mcp-servers.txt", content, dry_run, quiet, label="mcp-servers")


def dump_bashrc(out_dir: Path, dry_run: bool, quiet: bool) -> None:
    """Snapshot ~/.bashrc so the user's shell config (env vars, aliases, functions)
    is git-backed in the agents repo. It is the only place these live — there is
    no other backup (the `saveconfig` alias target may not exist)."""
    bashrc = HOME / ".bashrc"
    if not bashrc.exists():
        return
    try:
        body = bashrc.read_text(encoding="utf-8")
    except OSError:
        return
    header = (
        "# Snapshot of ~/.bashrc — auto-generated by executions/dump_system_state.py\n"
        "# Source of truth: the live ~/.bashrc. Edit it (or via /update-bashrc), not this file.\n"
        "# Regenerated at every session-debrief and committed to the agents repo.\n"
        "# (Contains no secrets by convention — keys live in personal/secrets/.env.)\n"
        "\n"
    )
    write_if_changed(out_dir / "bashrc.snapshot", header + body, dry_run, quiet, label="bashrc")


def write_readme(out_dir: Path, dry_run: bool, quiet: bool) -> None:
    """Write a small README so future readers understand what this directory is."""
    readme = """# system-state/ — Auto-Dumped Live Infrastructure

These files are deterministic snapshots of the operator's live infrastructure as of the last
`executions/dump_system_state.py` run (which fires at every `/session-debrief` via
postflight.sh step 0c).

| File | Source | Purpose |
|------|--------|---------|
| `crontab.txt` | `crontab -l` | Active cron jobs (Pulse AW, PR digest, transcript extractor, etc.) |
| `claude-hooks.json` | `~/.claude/settings.json` (hooks block) | All active Claude Code hooks |
| `claude-settings-public.json` | `~/.claude/settings.json` (full, secrets redacted) | Settings backup (env, permissions, statusline, model, etc.) |
| `installed-mcp-servers.txt` | `claude mcp list` (live local registry) | Local MCP servers + launch command (health suffix stripped) |
| `bashrc.snapshot` | `~/.bashrc` | Shell config backup: env vars, aliases, functions |
| `README.md` | This script | What you're reading |

**Companion documentation:** the personal layer's `context/indexed/active-systems.md` is the manual
overview (the *why* — purpose, log location, failure mode for each system). This
directory is the *exact what* — current configuration as committed.

**If they diverge:** the dump is the truth, the manual overview is stale — fix
the overview.

**Regeneration:** `python3 ~/ai-workspace/team-lib/executions/dump_system_state.py`.
Idempotent. Re-running without changes produces no diff.
"""
    write_if_changed(out_dir / "README.md", readme, dry_run, quiet, label="README")


def write_if_changed(path: Path, content: str, dry_run: bool, quiet: bool, *, label: str) -> None:
    """Write content only if different from current file (or file is missing)."""
    existing = ""
    if path.exists():
        try:
            existing = path.read_text(encoding="utf-8")
        except OSError:
            existing = ""

    if existing == content:
        if not quiet:
            print(f"  {label}: unchanged")
        return

    if dry_run:
        print(f"  {label}: WOULD WRITE ({len(content)} bytes) → {path}")
        return

    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content, encoding="utf-8")
    if not quiet:
        print(f"  {label}: wrote {len(content)} bytes → {path}")


def main() -> int:
    parser = argparse.ArgumentParser(description="Dump live infrastructure state to git-backed files.")
    parser.add_argument("--dry-run", action="store_true", help="Show what would change, write nothing")
    parser.add_argument("--quiet", action="store_true", help="Minimal output")
    parser.add_argument("--output-dir", type=Path, default=OUTPUT_DIR, help=f"Output directory (default: {OUTPUT_DIR})")
    args = parser.parse_args()

    out_dir = args.output_dir
    if not args.quiet:
        print(f"Dumping system state → {out_dir}")
        if args.dry_run:
            print("  (dry run — no files will be written)")

    out_dir.mkdir(parents=True, exist_ok=True)

    dump_crontab(out_dir, args.dry_run, args.quiet)
    dump_claude_hooks_and_settings(out_dir, args.dry_run, args.quiet)
    dump_mcp_servers(out_dir, args.dry_run, args.quiet)
    dump_bashrc(out_dir, args.dry_run, args.quiet)
    write_readme(out_dir, args.dry_run, args.quiet)

    if not args.quiet:
        print("Done.")
    return 0


def run() -> int:
    """Programmatic entry point per AGENTS.md Operating Principle #5 (chained execution)."""
    return main()


if __name__ == "__main__":
    sys.exit(main())
