#!/usr/bin/env python3
# ---
# template: execution
# version: 1.0.0
# summary: "Converts Claude Code session JSONL files into filtered, human-readable markdown transcripts. Streaming, idempotent, no LLM, stdlib-only. Outputs to agents/your-agent/transcripts/."
# created: 2026-04-30
# last_updated: 2026-04-30
# maintainer: pvragon
# ---
"""
Extract Session Transcripts

Reads Claude Code session JSONL files from ~/.claude/projects/*/
and outputs filtered markdown transcripts to:
  ~/ai-workspace/agents/your-agent/transcripts/

What is extracted:
  - User prompts (full text)
  - Assistant text responses (no tool JSON)
  - Tool breadcrumbs (file paths for Read/Edit/Write; counts for Bash)

What is dropped:
  - Tool call parameters and results
  - System prompts / <system-reminder> blocks
  - Thinking/reasoning blocks
  - Base64 / binary content
  - Compaction summaries
  - Subagent messages (isSidechain: true)

Usage:
    python3 extract_session_transcripts.py                          # All sessions, skip up-to-date
    python3 extract_session_transcripts.py --days 7                 # Only sessions from last 7 days
    python3 extract_session_transcripts.py --project /path/to/proj  # Single project
    python3 extract_session_transcripts.py --session-id <uuid>      # Single session
    python3 extract_session_transcripts.py --force                  # Re-extract everything
    python3 extract_session_transcripts.py --verbose                # Verbose output
"""

import argparse
import glob
import json
import os
import re
import sys
from datetime import datetime, timezone, timedelta
from pathlib import Path
from typing import Optional


# --- Paths ---
CLAUDE_PROJECTS_DIR = Path.home() / ".claude" / "projects"
OUTPUT_DIR = Path.home() / "ai-workspace" / "agents" / "your-agent" / "transcripts"
INDEX_FILE = OUTPUT_DIR / "TRANSCRIPT-INDEX.md"

# Resume gap threshold in seconds (1 hour)
RESUME_GAP_SECONDS = 3600

# Pattern to detect system/caveat injections in user messages
_SYSTEM_CONTENT_PATTERNS = [
    re.compile(r"<local-command-caveat>", re.IGNORECASE),
    re.compile(r"<system-reminder>", re.IGNORECASE),
    re.compile(r"^Caveat: The messages below were generated by the user while running local commands", re.MULTILINE),
    re.compile(r"<command-name>/clear</command-name>", re.IGNORECASE),
]

# Pattern for YYMMDD prefix
_YYMMDD_RE = re.compile(r"^\d{6}")


# ---------------------------------------------------------------------------
# Naming helpers
# ---------------------------------------------------------------------------

def _slugify(text: str) -> str:
    """Convert text to a filesystem-safe slug."""
    text = text.lower().strip()
    text = re.sub(r"[^\w\s-]", "", text)
    text = re.sub(r"[\s_]+", "-", text)
    text = re.sub(r"-+", "-", text)
    return text.strip("-")[:80]


def _derive_filename(entry: dict) -> str:
    """
    Derive the output filename for a session according to the naming rule:

    1. If summary was explicitly set (/rename) and already has YYMMDD prefix → use as-is.
    2. If summary was explicitly set but no YYMMDD prefix → prepend session-start date.
    3. If not renamed (summary == firstPrompt or truncation) → YYMMDD-HHMM-<first-3-words>.md
    """
    summary = (entry.get("summary") or "").strip()
    first_prompt = (entry.get("firstPrompt") or "").strip()
    created = entry.get("created", "")

    # Parse session start date
    try:
        dt = datetime.fromisoformat(created.replace("Z", "+00:00"))
        # Convert to local time
        local_dt = dt.astimezone()
        date_prefix = local_dt.strftime("%y%m%d")
        time_prefix = local_dt.strftime("%H%M")
    except (ValueError, OSError):
        date_prefix = "000000"
        time_prefix = "0000"

    # Detect if summary is a renamed (deliberate) title or just a truncated firstPrompt.
    # If summary starts with the same ~30 chars as firstPrompt, treat as NOT renamed.
    is_renamed = bool(summary) and not (
        summary[:30] == first_prompt[:30] or
        (first_prompt and first_prompt.startswith(summary))
    )

    if is_renamed:
        slug = _slugify(summary)
        if _YYMMDD_RE.match(slug):
            # Already has date prefix — use as-is
            return f"{slug}.md"
        else:
            return f"{date_prefix}-{slug}.md"
    else:
        # Fallback: YYMMDD-HHMM-<first-3-words>
        words = re.split(r"\s+", re.sub(r"[^\w\s]", " ", first_prompt.lower()).strip())
        word_slug = "-".join(w for w in words[:3] if w)[:40]
        if not word_slug:
            word_slug = entry.get("sessionId", "unknown")[:8]
        return f"{date_prefix}-{time_prefix}-{word_slug}.md"


# ---------------------------------------------------------------------------
# Duration formatting
# ---------------------------------------------------------------------------

def _format_duration(seconds: float) -> str:
    """Format seconds into a human-readable duration string."""
    if seconds < 60:
        return f"{int(seconds)}s"
    elif seconds < 3600:
        mins = int(seconds // 60)
        return f"{mins}m"
    else:
        hours = int(seconds // 3600)
        mins = int((seconds % 3600) // 60)
        if mins:
            return f"{hours}h {mins}m"
        return f"{hours}h"


# ---------------------------------------------------------------------------
# Content extraction helpers
# ---------------------------------------------------------------------------

def _is_system_content(text: str) -> bool:
    """Return True if the text is a system/caveat injection to suppress."""
    for pat in _SYSTEM_CONTENT_PATTERNS:
        if pat.search(text):
            return True
    return False


def _extract_user_text(message: dict) -> Optional[str]:
    """
    Extract plain user text from a message dict.
    Returns None if the message should be skipped (tool results, system injections, empty).
    """
    content = message.get("content", "")

    if isinstance(content, str):
        text = content.strip()
        if not text or _is_system_content(text):
            return None
        # Strip XML-style caveat wrappers
        text = re.sub(r"<local-command-caveat>.*?</local-command-caveat>", "", text, flags=re.DOTALL).strip()
        text = re.sub(r"<system-reminder>.*?</system-reminder>", "", text, flags=re.DOTALL).strip()
        text = re.sub(r"<[^>]+>", "", text).strip()  # remaining tags
        return text if text else None

    if isinstance(content, list):
        # If any block is tool_result, skip the entire message (it's a tool return)
        has_tool_result = any(
            isinstance(b, dict) and b.get("type") == "tool_result"
            for b in content
        )
        if has_tool_result:
            return None

        # Collect text blocks
        parts = []
        for block in content:
            if not isinstance(block, dict):
                continue
            if block.get("type") == "text":
                text = block.get("text", "").strip()
                if text and not _is_system_content(text):
                    # Strip XML caveat wrappers
                    text = re.sub(r"<local-command-caveat>.*?</local-command-caveat>", "", text, flags=re.DOTALL).strip()
                    text = re.sub(r"<system-reminder>.*?</system-reminder>", "", text, flags=re.DOTALL).strip()
                    text = re.sub(r"<[^>]+>", "", text).strip()
                    if text:
                        parts.append(text)
        return "\n".join(parts) if parts else None

    return None


def _extract_assistant_content(message: dict) -> tuple[str, list[dict]]:
    """
    Extract (text_output, tool_calls) from an assistant message.

    Returns:
        text_output: concatenated text content (stripped of thinking/tool_use)
        tool_calls: list of {"name": str, "input": dict} for each tool_use block
    """
    content = message.get("content", "")
    text_parts = []
    tool_calls = []

    if isinstance(content, str):
        return content.strip(), []

    if isinstance(content, list):
        for block in content:
            if not isinstance(block, dict):
                continue
            btype = block.get("type", "")
            if btype == "text":
                text = block.get("text", "").strip()
                if text:
                    text_parts.append(text)
            elif btype == "tool_use":
                tool_calls.append({
                    "name": block.get("name", ""),
                    "input": block.get("input", {}),
                })
            elif btype == "thinking":
                pass  # Drop thinking blocks
            # Drop tool_result, etc.

    return "\n".join(text_parts), tool_calls


# ---------------------------------------------------------------------------
# Breadcrumb builder
# ---------------------------------------------------------------------------

def _build_breadcrumb(tool_calls: list[dict]) -> Optional[str]:
    """
    Build a compact breadcrumb string from a list of tool calls in a single turn.

    Format: > [Read: a.md, b.md | Edit: c.md | Bash: 2 commands]
    """
    if not tool_calls:
        return None

    # Group by tool type
    read_files: list[str] = []
    edit_files: list[str] = []
    write_files: list[str] = []
    notebook_files: list[str] = []
    bash_count = 0
    grep_count = 0
    grep_first: Optional[str] = None
    glob_count = 0
    glob_first: Optional[str] = None
    web_search_count = 0
    web_search_first: Optional[str] = None
    web_fetch_count = 0
    web_fetch_first: Optional[str] = None
    task_descriptions: list[str] = []
    skill_names: list[str] = []
    task_create_count = 0
    task_update_count = 0
    task_list_count = 0
    other: dict[str, int] = {}  # tool_name -> count

    for tc in tool_calls:
        name = tc.get("name", "")
        inp = tc.get("input", {}) or {}

        if name == "Read":
            fp = inp.get("file_path", "")
            if fp:
                read_files.append(os.path.basename(fp) if len(fp) > 40 else fp)
        elif name in ("Edit", "MultiEdit"):
            fp = inp.get("file_path", "")
            if fp:
                edit_files.append(os.path.basename(fp) if len(fp) > 40 else fp)
        elif name == "Write":
            fp = inp.get("file_path", "")
            if fp:
                write_files.append(os.path.basename(fp) if len(fp) > 40 else fp)
        elif name == "NotebookEdit":
            fp = inp.get("notebook_path", "")
            if fp:
                notebook_files.append(os.path.basename(fp) if len(fp) > 40 else fp)
        elif name == "Bash":
            bash_count += 1
        elif name in ("Grep", "GlobSearch"):
            if name == "Grep":
                grep_count += 1
                if grep_first is None:
                    q = inp.get("pattern", inp.get("query", ""))
                    if q and len(q) < 50:
                        grep_first = q
            else:
                glob_count += 1
                if glob_first is None:
                    q = inp.get("pattern", "")
                    if q and len(q) < 50:
                        glob_first = q
        elif name == "WebSearch":
            web_search_count += 1
            if web_search_first is None:
                q = inp.get("query", "")
                if q and len(q) < 60:
                    web_search_first = q
        elif name == "WebFetch":
            web_fetch_count += 1
            if web_fetch_first is None:
                url = inp.get("url", "")
                if url and len(url) < 60:
                    web_fetch_first = url
        elif name in ("Task", "Agent"):
            desc = inp.get("description", inp.get("prompt", ""))
            if desc:
                task_descriptions.append(str(desc)[:60])
        elif name == "Skill":
            skill_name = inp.get("skill", "")
            if skill_name:
                skill_names.append(skill_name)
        elif name in ("TaskCreate", "mcp__clickup__create_task"):
            task_create_count += 1
        elif name in ("TaskUpdate", "mcp__clickup__update_task"):
            task_update_count += 1
        elif name in ("TaskList", "mcp__clickup__get_tasks"):
            task_list_count += 1
        else:
            # Any other MCP or tool
            other[name] = other.get(name, 0) + 1

    parts = []

    if read_files:
        parts.append(f"Read: {', '.join(read_files[:5])}" + (f" +{len(read_files)-5}" if len(read_files) > 5 else ""))
    if edit_files:
        parts.append(f"Edit: {', '.join(edit_files[:5])}" + (f" +{len(edit_files)-5}" if len(edit_files) > 5 else ""))
    if write_files:
        parts.append(f"Write: {', '.join(write_files[:5])}" + (f" +{len(write_files)-5}" if len(write_files) > 5 else ""))
    if notebook_files:
        parts.append(f"NotebookEdit: {', '.join(notebook_files[:3])}")
    if bash_count:
        parts.append(f"Bash: {bash_count} command{'s' if bash_count > 1 else ''}")
    if grep_count:
        parts.append(f"Grep: {grep_count}" + (f" ('{grep_first}')" if grep_first else ""))
    if glob_count:
        parts.append(f"Glob: {glob_count}" + (f" ('{glob_first}')" if glob_first else ""))
    if web_search_count:
        parts.append(f"WebSearch: {web_search_count}" + (f" ('{web_search_first}')" if web_search_first else ""))
    if web_fetch_count:
        parts.append(f"WebFetch: {web_fetch_count}" + (f" ('{web_fetch_first}')" if web_fetch_first else ""))
    for desc in task_descriptions[:2]:
        parts.append(f"Task: {desc}")
    for sn in skill_names[:2]:
        parts.append(f"Skill: {sn}")
    if task_create_count:
        parts.append(f"TaskCreate: {task_create_count}")
    if task_update_count:
        parts.append(f"TaskUpdate: {task_update_count}")
    if task_list_count:
        parts.append(f"TaskList: {task_list_count}")
    for tool_name, count in other.items():
        # Abbreviate long MCP tool names
        short_name = tool_name.split("__")[-1] if "__" in tool_name else tool_name
        parts.append(f"{short_name}: {count}")

    if not parts:
        return None

    return f"> [{' | '.join(parts)}]"


# ---------------------------------------------------------------------------
# Core JSONL processor
# ---------------------------------------------------------------------------

def process_session(jsonl_path: Path, entry: dict, verbose: bool = False) -> Optional[dict]:
    """
    Stream-process a session JSONL file and return transcript data.

    Returns:
        dict with keys: frontmatter, body, filename, session_id
        None if the session has no meaningful content.
    """
    session_id = entry.get("sessionId", "")
    created = entry.get("created", "")
    project_path = entry.get("projectPath", "")
    project_name = os.path.basename(project_path) if project_path else "unknown"
    message_count_est = entry.get("messageCount", 0)

    # Metadata we'll collect
    first_timestamp: Optional[float] = None
    last_timestamp: Optional[float] = None
    tools_used: set[str] = set()
    files_touched: list[str] = []
    files_touched_set: set[str] = set()
    actual_message_count = 0

    # Body accumulation
    body_lines: list[str] = []

    # State machine
    prev_timestamp: Optional[float] = None
    pending_tool_calls: list[dict] = []  # tools accumulated after last assistant text

    def _flush_breadcrumb():
        """If there are pending tool calls, emit the breadcrumb."""
        nonlocal pending_tool_calls
        if pending_tool_calls:
            bc = _build_breadcrumb(pending_tool_calls)
            if bc:
                body_lines.append("")
                body_lines.append(bc)
            pending_tool_calls = []

    def _parse_ts(ts_val) -> Optional[float]:
        """Parse a timestamp (ISO string or ms-int) to POSIX seconds."""
        if ts_val is None:
            return None
        if isinstance(ts_val, str):
            try:
                dt = datetime.fromisoformat(ts_val.replace("Z", "+00:00"))
                return dt.timestamp()
            except (ValueError, OSError):
                return None
        if isinstance(ts_val, (int, float)):
            # Could be milliseconds or seconds
            if ts_val > 1e10:
                return ts_val / 1000.0
            return float(ts_val)
        return None

    line_num = 0
    try:
        with open(jsonl_path, "r", encoding="utf-8", errors="replace") as f:
            for raw_line in f:
                line_num += 1
                raw_line = raw_line.strip()
                if not raw_line:
                    continue
                try:
                    obj = json.loads(raw_line)
                except json.JSONDecodeError:
                    if verbose:
                        print(f"  WARN: malformed JSON at line {line_num} in {jsonl_path.name}", file=sys.stderr)
                    continue

                # Skip subagent messages
                if obj.get("isSidechain", False):
                    continue

                obj_type = obj.get("type", "")

                # Skip non-message types (custom-title, file-history-snapshot, summary, etc.)
                if obj_type not in ("user", "assistant"):
                    continue

                # Parse timestamp
                ts_raw = obj.get("timestamp") or obj.get("createdAt")
                ts = _parse_ts(ts_raw)

                if ts is not None:
                    if first_timestamp is None:
                        first_timestamp = ts
                    last_timestamp = ts

                    # Resume detection: gap > 1 hour
                    if prev_timestamp is not None and (ts - prev_timestamp) > RESUME_GAP_SECONDS:
                        dt_resume = datetime.fromtimestamp(ts).strftime("%Y-%m-%d")
                        body_lines.append("")
                        body_lines.append("---")
                        body_lines.append(f"[Session resumed {dt_resume}]")
                        body_lines.append("---")
                        body_lines.append("")
                    prev_timestamp = ts

                msg = obj.get("message", {})
                if not isinstance(msg, dict):
                    # Sometimes message is a string — treat as user text
                    if obj_type == "user" and isinstance(msg, str) and msg.strip():
                        if not _is_system_content(msg):
                            _flush_breadcrumb()
                            body_lines.append("")
                            body_lines.append(f"**the operator:** {msg.strip()}")
                            actual_message_count += 1
                    continue

                if obj_type == "user":
                    text = _extract_user_text(msg)
                    if text:
                        _flush_breadcrumb()
                        body_lines.append("")
                        body_lines.append(f"**the operator:** {text}")
                        actual_message_count += 1

                elif obj_type == "assistant":
                    text, tool_calls = _extract_assistant_content(msg)

                    # Emit any previous pending tool calls (from prior assistant turn with no text)
                    # Actually, flush happens before user messages. Here we handle consecutive
                    # assistant turns (rare but possible with tool_use pattern):
                    # Tool calls accumulate until the next user message.

                    if text:
                        body_lines.append("")
                        body_lines.append(f"**Rowan:** {text}")
                        actual_message_count += 1

                    # Accumulate tool calls for breadcrumb (emitted before next user message)
                    for tc in tool_calls:
                        tool_name = tc.get("name", "")
                        if tool_name:
                            tools_used.add(tool_name)
                            # Track files touched
                            inp = tc.get("input", {}) or {}
                            for key in ("file_path", "notebook_path"):
                                fp = inp.get(key, "")
                                if fp and fp not in files_touched_set:
                                    files_touched_set.add(fp)
                                    files_touched.append(fp)
                        pending_tool_calls.append(tc)

    except OSError as e:
        print(f"  ERROR reading {jsonl_path}: {e}", file=sys.stderr)
        return None

    # Flush any trailing tool calls
    _flush_breadcrumb()

    # Must have some content
    if actual_message_count == 0:
        if verbose:
            print(f"  SKIP (no content): {session_id[:12]}", file=sys.stderr)
        return None

    # --- Build frontmatter ---
    duration_str = "unknown"
    if first_timestamp is not None and last_timestamp is not None:
        dur = last_timestamp - first_timestamp
        duration_str = _format_duration(dur)

    # Parse date from created (or first_timestamp)
    try:
        if created:
            date_dt = datetime.fromisoformat(created.replace("Z", "+00:00")).astimezone()
        elif first_timestamp:
            date_dt = datetime.fromtimestamp(first_timestamp)
        else:
            date_dt = datetime.now()
        date_str = date_dt.strftime("%Y-%m-%d")
    except (ValueError, OSError):
        date_str = "unknown"

    session_name = (entry.get("summary") or "").strip() or session_id[:8]

    frontmatter_lines = [
        "---",
        f"session_id: {session_id}",
        f"date: {date_str}",
        f'name: "{session_name}"',
        f"project: {project_name}",
        f'duration_estimate: "{duration_str}"',
        "topics: []",
        f"tools_used: [{', '.join(sorted(tools_used))}]",
        "files_touched:",
    ]
    if files_touched:
        for fp in files_touched[:30]:  # cap at 30 files
            frontmatter_lines.append(f"  - {fp}")
    else:
        frontmatter_lines.append("  []")
    frontmatter_lines.append(f"message_count: {actual_message_count}")
    frontmatter_lines.append("---")

    # --- Build header ---
    header_lines = [
        "",
        f"# {session_name}",
        f"**{date_str}** | {project_name} | ~{duration_str}",
        "",
        "---",
    ]

    # Remove leading blank lines from body
    while body_lines and not body_lines[0].strip():
        body_lines.pop(0)

    full_content = (
        "\n".join(frontmatter_lines)
        + "\n"
        + "\n".join(header_lines)
        + "\n"
        + "\n".join(body_lines)
        + "\n"
    )

    filename = _derive_filename(entry)

    return {
        "filename": filename,
        "content": full_content,
        "session_id": session_id,
        "session_name": session_name,
        "date": date_str,
        "project": project_name,
        "actual_message_count": actual_message_count,
    }


# ---------------------------------------------------------------------------
# Index management
# ---------------------------------------------------------------------------

def _load_index_entries(index_path: Path) -> dict[str, dict]:
    """Load existing TRANSCRIPT-INDEX.md into a map of filename -> entry."""
    result: dict[str, dict] = {}
    if not index_path.exists():
        return result
    # Parse the markdown table
    with open(index_path, "r", encoding="utf-8") as f:
        for line in f:
            line = line.strip()
            if not line.startswith("|") or line.startswith("| Date"):
                continue
            cols = [c.strip() for c in line.split("|") if c.strip()]
            if len(cols) >= 4:
                date, session, project, file_ref = cols[0], cols[1], cols[2], cols[3]
                filename = file_ref.strip("`")
                result[filename] = {"date": date, "session": session, "project": project}
    return result


def _rebuild_index(output_dir: Path, index_path: Path) -> None:
    """Rebuild TRANSCRIPT-INDEX.md from all transcript files in output_dir."""
    transcripts = sorted(output_dir.glob("*.md"))
    transcripts = [t for t in transcripts if t.name != "TRANSCRIPT-INDEX.md"]

    rows: list[tuple[str, str, str, str]] = []  # (date, session, project, filename)

    for t in transcripts:
        # Parse frontmatter for metadata
        date_val = ""
        session_val = t.stem
        project_val = ""
        with open(t, "r", encoding="utf-8") as f:
            in_fm = False
            for line in f:
                line = line.rstrip()
                if line == "---":
                    if not in_fm:
                        in_fm = True
                        continue
                    else:
                        break
                if in_fm:
                    if line.startswith("date:"):
                        date_val = line.split(":", 1)[1].strip()
                    elif line.startswith("name:"):
                        session_val = line.split(":", 1)[1].strip().strip('"')
                    elif line.startswith("project:"):
                        project_val = line.split(":", 1)[1].strip()
        rows.append((date_val, session_val, project_val, t.name))

    # Sort by date desc
    rows.sort(key=lambda r: r[0], reverse=True)

    lines = [
        "# Transcript Index",
        "",
        "| Date | Session | Project | File |",
        "|------|---------|---------|------|",
    ]
    for date_val, session_val, project_val, filename in rows:
        # Truncate long session names in index (full name is in the file's frontmatter)
        display_name = session_val if len(session_val) <= 60 else session_val[:57] + "..."
        lines.append(f"| {date_val} | {display_name} | {project_val} | `{filename}` |")

    lines.append("")
    lines.append(f"*{len(rows)} transcript{'s' if len(rows) != 1 else ''} total*")
    lines.append("")

    with open(index_path, "w", encoding="utf-8") as f:
        f.write("\n".join(lines) + "\n")


# ---------------------------------------------------------------------------
# Main extraction loop
# ---------------------------------------------------------------------------

def load_sessions_index(project_dir: Path) -> list[dict]:
    """Load sessions-index.json from a project directory. Returns list of entries."""
    idx_path = project_dir / "sessions-index.json"
    if not idx_path.exists():
        return []
    try:
        with open(idx_path, "r", encoding="utf-8") as f:
            data = json.load(f)
        if isinstance(data, dict):
            return data.get("entries", [])
        if isinstance(data, list):
            return data
    except (json.JSONDecodeError, OSError) as e:
        print(f"  WARN: could not load {idx_path}: {e}", file=sys.stderr)
    return []


def run(
    days: Optional[int] = None,
    project: Optional[str] = None,
    session_id: Optional[str] = None,
    force: bool = False,
    verbose: bool = False,
) -> dict:
    """
    Main extraction runner. Returns summary stats dict.

    Args:
        days: Only process sessions from the last N days.
        project: Limit to a specific project path (basename or full path).
        session_id: Limit to a single session ID.
        force: Re-extract even if transcript is up-to-date.
        verbose: Print detailed progress.
    """
    OUTPUT_DIR.mkdir(parents=True, exist_ok=True)

    # Collect all project dirs
    project_dirs = sorted(CLAUDE_PROJECTS_DIR.glob("*/"))

    # Filter to a specific project if requested
    if project:
        proj_basename = os.path.basename(project.rstrip("/"))
        project_dirs = [
            p for p in project_dirs
            if p.name == proj_basename or p.name.endswith(proj_basename.replace("/", "-"))
        ]
        if not project_dirs:
            # Try to match by contained project path
            project_dirs = [
                p for p in sorted(CLAUDE_PROJECTS_DIR.glob("*/"))
                if project.rstrip("/").replace("/", "-").lstrip("-") in p.name
            ]

    # Cutoff date for --days filter
    cutoff: Optional[datetime] = None
    if days:
        cutoff = datetime.now(timezone.utc) - timedelta(days=days)

    stats = {
        "processed": 0,
        "skipped_uptodate": 0,
        "skipped_no_content": 0,
        "errors": 0,
        "total_input_bytes": 0,
        "total_output_bytes": 0,
    }

    for proj_dir in project_dirs:
        if verbose:
            print(f"\nProject dir: {proj_dir.name}")

        entries = load_sessions_index(proj_dir)
        if not entries:
            # Fallback: enumerate JSONL files without index
            jsonl_files = [f for f in proj_dir.glob("*.jsonl") if not f.name.startswith("agent-")]
            entries = [
                {
                    "sessionId": f.stem,
                    "fullPath": str(f),
                    "firstPrompt": "",
                    "summary": "",
                    "created": "",
                    "projectPath": str(proj_dir),
                }
                for f in jsonl_files
            ]

        for entry in entries:
            sid = entry.get("sessionId", "")

            # Filter by session_id
            if session_id and sid != session_id:
                continue

            # Filter sidechains at index level
            if entry.get("isSidechain", False):
                continue

            # Filter by date
            if cutoff:
                created_str = entry.get("created", "")
                if created_str:
                    try:
                        created_dt = datetime.fromisoformat(created_str.replace("Z", "+00:00"))
                        if created_dt < cutoff:
                            continue
                    except (ValueError, OSError):
                        pass

            # Resolve JSONL path
            jsonl_path_str = entry.get("fullPath", "")
            if jsonl_path_str:
                jsonl_path = Path(jsonl_path_str)
            else:
                jsonl_path = proj_dir / f"{sid}.jsonl"

            if not jsonl_path.exists():
                if verbose:
                    print(f"  SKIP (missing): {sid[:12]}", file=sys.stderr)
                continue

            jsonl_mtime = jsonl_path.stat().st_mtime
            input_size = jsonl_path.stat().st_size

            # Determine expected output filename (estimate only — need entry data)
            # We'll check idempotency after computing the filename
            expected_name = _derive_filename(entry)
            out_path = OUTPUT_DIR / expected_name

            # Idempotency check: skip if transcript is newer than JSONL
            if not force and out_path.exists():
                transcript_mtime = out_path.stat().st_mtime
                if transcript_mtime >= jsonl_mtime:
                    stats["skipped_uptodate"] += 1
                    if verbose:
                        print(f"  SKIP (up-to-date): {expected_name}")
                    continue

            if verbose:
                print(f"  Processing: {sid[:12]}... ({input_size:,} bytes)")

            result = process_session(jsonl_path, entry, verbose=verbose)
            if result is None:
                stats["skipped_no_content"] += 1
                continue

            # Write output
            final_out_path = OUTPUT_DIR / result["filename"]
            try:
                with open(final_out_path, "w", encoding="utf-8") as f:
                    f.write(result["content"])
                output_size = final_out_path.stat().st_size
                stats["processed"] += 1
                stats["total_input_bytes"] += input_size
                stats["total_output_bytes"] += output_size
                if verbose:
                    ratio = output_size / input_size * 100 if input_size else 0
                    print(f"  WROTE: {result['filename']} ({output_size:,} bytes, {ratio:.1f}% of input)")
            except OSError as e:
                print(f"  ERROR writing {final_out_path}: {e}", file=sys.stderr)
                stats["errors"] += 1

    # Rebuild index
    _rebuild_index(OUTPUT_DIR, INDEX_FILE)

    return stats


# ---------------------------------------------------------------------------
# CLI entrypoint
# ---------------------------------------------------------------------------

if __name__ == "__main__":
    parser = argparse.ArgumentParser(
        description="Extract Claude Code session JSONL files into filtered markdown transcripts"
    )
    parser.add_argument(
        "--days",
        type=int,
        metavar="N",
        help="Only process sessions from the last N days",
    )
    parser.add_argument(
        "--project",
        type=str,
        metavar="PATH",
        help="Limit to sessions from a specific project path",
    )
    parser.add_argument(
        "--session-id",
        type=str,
        metavar="UUID",
        help="Process a single session by ID",
    )
    parser.add_argument(
        "--force",
        action="store_true",
        help="Re-extract even if transcripts are already up-to-date",
    )
    parser.add_argument(
        "--verbose",
        action="store_true",
        help="Print detailed progress to stdout",
    )
    args = parser.parse_args()

    stats = run(
        days=args.days,
        project=args.project,
        session_id=args.session_id,
        force=args.force,
        verbose=args.verbose,
    )

    print(f"\nDone.")
    print(f"  Processed:          {stats['processed']}")
    print(f"  Skipped (current):  {stats['skipped_uptodate']}")
    print(f"  Skipped (no content): {stats['skipped_no_content']}")
    print(f"  Errors:             {stats['errors']}")
    if stats["total_input_bytes"]:
        ratio = stats["total_output_bytes"] / stats["total_input_bytes"] * 100
        print(f"  Input:  {stats['total_input_bytes']:,} bytes")
        print(f"  Output: {stats['total_output_bytes']:,} bytes ({ratio:.1f}% of input)")
    print(f"\nTranscripts: {OUTPUT_DIR}")
    print(f"Index:       {INDEX_FILE}")
