#!/usr/bin/env bash
#
# bootstrap_local.sh
# Creates/updates the ai-workspace scaffold with Functional Topology.
# Generates workspace-manifest.yaml for machine-agnostic path resolution.
# Idempotent: running multiple times will NOT overwrite existing files.
#
set -euo pipefail

WORKSPACE_ROOT="${HOME}/ai-workspace"
MANIFEST_PATH="${HOME}/.ai-workspace-manifest.yaml"

# Helper: create directory if it doesn't exist
ensure_dir() {
    local dir="$1"
    if [[ ! -d "$dir" ]]; then
        mkdir -p "$dir"
        echo "Created directory: $dir"
    fi
}

# Helper: create file if it doesn't exist
ensure_file() {
    local file="$1"
    local content="$2"
    if [[ ! -f "$file" ]]; then
        echo "$content" > "$file"
        echo "Created file: $file"
    fi
}

# ============================================================================
# DIRECTORY STRUCTURE (Functional Topology)
# ============================================================================

echo "=== Creating ai-workspace structure (Functional Topology) ==="

# Layer 0: Personal (human-only)
ensure_dir "${WORKSPACE_ROOT}/personal/notes"
ensure_dir "${WORKSPACE_ROOT}/personal/scratch"
ensure_dir "${WORKSPACE_ROOT}/personal/preferences"
ensure_dir "${WORKSPACE_ROOT}/personal/secrets"

# Layer 1: Pvragon Library (Team Repo - shared canonical OS)
# TODO: Replace with: git clone https://github.com/Pvragon/pvragon-ai-library.git team-lib
ensure_dir "${WORKSPACE_ROOT}/team-lib/directives"
ensure_dir "${WORKSPACE_ROOT}/team-lib/context/global"
ensure_dir "${WORKSPACE_ROOT}/team-lib/context/indexed"
ensure_dir "${WORKSPACE_ROOT}/team-lib/personas"
ensure_dir "${WORKSPACE_ROOT}/team-lib/skills"
ensure_dir "${WORKSPACE_ROOT}/team-lib/executions"
ensure_dir "${WORKSPACE_ROOT}/team-lib/harnesses"
ensure_dir "${WORKSPACE_ROOT}/team-lib/registry"
ensure_dir "${WORKSPACE_ROOT}/team-lib/logs"

# Layer 2: Private Library (Private Repo - personal overlay)
# TODO: Replace with: git clone https://github.com/jkhereford/private-ai-library.git my-lib
ensure_dir "${WORKSPACE_ROOT}/my-lib/archive"
ensure_dir "${WORKSPACE_ROOT}/my-lib/backlog"
ensure_dir "${WORKSPACE_ROOT}/my-lib/directives"
ensure_dir "${WORKSPACE_ROOT}/my-lib/context/global"
ensure_dir "${WORKSPACE_ROOT}/my-lib/context/indexed"
ensure_dir "${WORKSPACE_ROOT}/my-lib/personas"
ensure_dir "${WORKSPACE_ROOT}/my-lib/skills"
ensure_dir "${WORKSPACE_ROOT}/my-lib/executions"
ensure_dir "${WORKSPACE_ROOT}/my-lib/harnesses"
ensure_dir "${WORKSPACE_ROOT}/my-lib/registry"
ensure_dir "${WORKSPACE_ROOT}/my-lib/logs"
ensure_dir "${WORKSPACE_ROOT}/my-lib/runtime/intermediates"
ensure_dir "${WORKSPACE_ROOT}/my-lib/runtime/deliverables"
ensure_dir "${WORKSPACE_ROOT}/my-lib/runtime/logs"

# Layer 3: Workbench (All project repos - private and team)
ensure_dir "${WORKSPACE_ROOT}/projects"

# Admin scripts (now within team-lib)
ensure_dir "${WORKSPACE_ROOT}/team-lib/_admin"

# ============================================================================
# ROOT-LEVEL INDEX.MD
# ============================================================================

ensure_file "${WORKSPACE_ROOT}/index.md" "# AI Workspace (Functional Topology)

## Purpose
Root of the Pvragon AI Workspace—a 4-layer functional hierarchy for agentic development and automation.

## Layers

| Layer | Directory | Purpose |
|-------|-----------|---------|
| **0** | \`personal/\` | Local machine overrides (human-only) |
| **1** | \`team-lib/\` | System Standard Library (shared OS) |
| **2** | \`my-lib/\` | User Extension Library (personal overlay) |
| **3** | \`projects/\` | Active Development Factory (all projects) |

## Operational Modes

| Mode | Location | Behavior |
|------|----------|----------|
| STOP | Root (\`~/ai-workspace/\`) | No work permitted; route to scope |
| Automation | Libraries (\`team-lib/\`, \`my-lib/\`) | DOE automator mode |
| Engineering | Workbench (\`projects/*\`) | Builder mode; read specs, write code |

## Root Symlinks
- \`CLAUDE.md\` → \`team-lib/context/global/template-agent-safety.md\`
- \`workspace.yaml\` → \`team-lib/registry/workspace.yaml\`

## Machine-Agnostic Path Resolution
- Agents load \`~/.ai-workspace-manifest.yaml\` for all path references
- Generated by \`bootstrap_local.sh\` on each machine
- Enables deployment across different computers and users

## Key Rule
**Do not work at root.** Navigate to a numbered scope first.
"

# ============================================================================
# PERSONAL
# ============================================================================

ensure_file "${WORKSPACE_ROOT}/personal/index.md" "# personal

Private human workspace. Agents should not access unless directed.

- \`notes/\` - Personal notes
- \`scratch/\` - Temporary work
- \`preferences/\` - Personal config
"

ensure_file "${WORKSPACE_ROOT}/personal/preferences/personal.md" "# Personal Preferences

User: (your name here)
"

ensure_file "${WORKSPACE_ROOT}/personal/notes/index.md" "# notes

Personal notes and documentation.
"

ensure_file "${WORKSPACE_ROOT}/personal/scratch/index.md" "# scratch

Temporary work area.
"

ensure_file "${WORKSPACE_ROOT}/personal/preferences/index.md" "# preferences

Personal configuration and settings.
"

# ============================================================================
# TEAM-LIB (TEAM REPO BOUNDARY)
# ============================================================================

ensure_file "${WORKSPACE_ROOT}/team-lib/README.md" "# Pvragon AI Library

**The standardized operating system for agentic development.**

This repository is the **Layer 1 (Shared)** foundation of the Pvragon AI Workspace. It provides the shared tooling, context, and directives that enable consistent, high-quality agent performance across the team.

---

## 🚀 Quick Start

### [**→ Start Here: Getting Started Guide**](_admin/GETTING_STARTED.md)
*Follow this guide to set up your environment from zero to fully functional.*

### [**→ Operating Manual: Workspace Reference**](context/indexed/workspace-reference.md)
*The definitive guide to the workspace topology, layers, and usage rules.*

---

## 🏗️ Functional Stack

A high-level overview of the standard library components:

| Layer | Directory | Purpose |
|-------|-----------|---------| 
| **Directives** | \`directives/\` | High-level instructions and behavioral rules (SOPs) |
| **Context** | \`context/\` | Team knowledge base (Global + Indexed packs) |
| **Personas** | \`personas/\` | Team-approved agent identities |
| **Skills** | \`skills/\` | Shared capability modules and tools |
| **Executions** | \`executions/\` | Deterministic scripts for reliable automation |
| **Harnesses** | \`harnesses/\` | Test frameworks and evaluation suites |
| **Registry** | \`registry/\` | Manifests cataloging available resources |
| **Logs** | \`logs/\` | Team execution audits |

## 📂 Directory Structure

\`\`\`
team-lib/
├── _admin/             # Bootstrap, validation, and setup scripts
├── directives/         # Behavioral rules (SOPs)
├── context/            # Knowledge base
│   ├── global/         # Always-on context
│   └── indexed/        # On-demand context packs
├── personas/           # Agent configurations
├── skills/             # Capability modules (Tools)
├── executions/         # Scripts (Actions)
├── harnesses/          # Testing frameworks
├── registry/           # Resource manifests (YAML)
└── logs/               # Execution logs
\`\`\`

## ⚖️ Governance & Standards

**This library is governed by strict quality controls.**
Before contributing, you **must** read the [**Team Library Governance Directive**](directives/team-library-governance.md).

**Key Rules:**
1.  **No Personal Code:** If it has your name or hardcoded home path, it doesn't belong here.
2.  **Pull Request Required:** Direct pushes to \`main\` are forbidden.
3.  **Strict Naming:** \`kebab-case\` for files, \`snake_case\` for python.

## 🤝 How to Contribute

1.  **Create** resources in the appropriate directory (e.g., new SOP in \`directives/\`).
2.  **Register** new resources in the relevant \`registry/\` manifest.
3.  **Test** using \`harnesses/\` before deployment.
4.  **Submit** a Pull Request for review.
"

# Template files with versioning
ensure_file "${WORKSPACE_ROOT}/team-lib/context/global/template-agent-safety.md" "---
template: agent-safety
version: 1.0.0
last_updated: $(date +%Y-%m-%d)
maintainer: pvragon
---

# 🛑 STOP - WRONG DIRECTORY
You are at the **Workspace Root** (\`~/ai-workspace\`).
**NO WORK IS PERMITTED HERE.**

### Instructions
1. **Do not create files.**
2. **Do not run commands.**
3. **Do not make changes.**

**Action:** Ask the user to move to a scope: \`personal/\`, \`team-lib/\`, \`my-lib/\`, or \`projects/\`.
"

ensure_file "${WORKSPACE_ROOT}/team-lib/context/global/template-agent-engineering.md" "---
template: agent-engineering
version: 1.0.0
last_updated: $(date +%Y-%m-%d)
maintainer: pvragon
---

# Engineering Mode (Builder Framework)
**Role:** You are a Senior Engineer.
**Rule:** Read \`docs/specs/\`. Write source code. Run tests.
**Registry Bridge:** Always load \`~/.ai-workspace-manifest.yaml\` to access workspace paths and shared tools.
"

ensure_file "${WORKSPACE_ROOT}/team-lib/context/global/index.md" "# global

Always-on context for team operations.
"

ensure_file "${WORKSPACE_ROOT}/team-lib/context/indexed/index.md" "# indexed

On-demand context packs. Query when specific info is needed.
"

ensure_file "${WORKSPACE_ROOT}/team-lib/context/index.md" "# context

Agent memory and context.

- \`global/\` - Always-on context
- \`indexed/\` - On-demand context packs
"

ensure_file "${WORKSPACE_ROOT}/team-lib/directives/index.md" "# directives

SOPs in Markdown defining goals, inputs, tools, outputs, edge cases.
"

ensure_file "${WORKSPACE_ROOT}/team-lib/executions/index.md" "# executions

Deterministic Python scripts. Reliable, testable, fast.
"

ensure_file "${WORKSPACE_ROOT}/team-lib/personas/index.md" "# personas

Agent identity configurations.
"

ensure_file "${WORKSPACE_ROOT}/team-lib/skills/index.md" "# skills

Reusable capability modules.
"

ensure_file "${WORKSPACE_ROOT}/team-lib/harnesses/index.md" "# harnesses

Test and evaluation frameworks.
"

ensure_file "${WORKSPACE_ROOT}/team-lib/logs/index.md" "# logs

Execution logs and audit trails.
"

ensure_file "${WORKSPACE_ROOT}/team-lib/registry/index.md" "# registry

Manifests cataloging available resources.
"

# ============================================================================
# MY-LIB (PRIVATE REPO BOUNDARY)
# ============================================================================

ensure_file "${WORKSPACE_ROOT}/my-lib/README.md" "# my-lib
 
 ## Overview
 This repository contains private AI agent resources for personal use. It houses the complete functional stack for configuring and running AI agents in a private context.
 
 ## Functional Stack
 
 | Layer | Directory | Purpose |
 |-------|-----------|---------|
 | **Directives** | \`directives/\` | High-level instructions and behavioral rules for agents |
 | **Context** | \`context/\` | Background information and knowledge bases (global + indexed) |
 | **Personas** | \`personas/\` | Agent identity definitions and personality configurations |
 | **Skills** | \`skills/\` | Reusable capability modules and tool definitions |
 | **Executions** | \`executions/\` | Deterministic scripts and tools |
 | **Harnesses** | \`harnesses/\` | Test and evaluation frameworks for agents |
 | **Registry** | \`registry/\` | Manifests cataloging available resources |
 | **Backlog** | \`backlog/\` | Future plans, paused projects, and ideas to revisit |
 | **Archive** | \`archive/\` | Completed plans and historical documentation |
 | **Logs** | \`logs/\` | Execution logs and audit trails |
 
 ## Directory Structure
 \`\`\`
 my-lib/
 ├── archive/            # Completed plans and historical docs
 ├── backlog/            # Future plans and paused projects
 ├── context/
 │   ├── global/         # Always-available context
 │   └── indexed/        # Searchable/retrievable context
 ├── directives/         # Behavioral rules and instructions
 ├── executions/         # Workflow definitions
 ├── harnesses/          # Testing frameworks
 ├── logs/               # Execution logs
 ├── personas/           # Agent identity configurations
 ├── registry/           # Resource manifests
 ├── runtime/            # Local execution outputs
 └── skills/             # Capability modules
 \`\`\`
 
 ## How to Contribute
 1. Create resources in the appropriate directory
 2. Register new resources in the relevant registry manifest
 3. Test using harnesses before production use
 4. Document changes in commit messages
 
 ## Usage
 Agents reference this workspace to load directives, personas, skills, and context for private tasks.
 "

ensure_file "${WORKSPACE_ROOT}/my-lib/context/global/index.md" "# global

Personal always-on context.
"

ensure_file "${WORKSPACE_ROOT}/my-lib/context/indexed/index.md" "# indexed

Personal on-demand context.
"

ensure_file "${WORKSPACE_ROOT}/my-lib/context/index.md" "# context

Personal agent memory and context.

- \`global/\` - Always-on context
- \`indexed/\` - On-demand context packs
"

ensure_file "${WORKSPACE_ROOT}/my-lib/directives/index.md" "# directives

Personal SOPs (staging).
"

ensure_file "${WORKSPACE_ROOT}/my-lib/executions/index.md" "# executions

Personal scripts (staging).
"

ensure_file "${WORKSPACE_ROOT}/my-lib/personas/index.md" "# personas

Personal agent configs.
"

ensure_file "${WORKSPACE_ROOT}/my-lib/skills/index.md" "# skills

Personal capability modules.
"

ensure_file "${WORKSPACE_ROOT}/my-lib/harnesses/index.md" "# harnesses

Personal test frameworks.
"

ensure_file "${WORKSPACE_ROOT}/my-lib/logs/index.md" "# logs

Personal execution logs.
"

ensure_file "${WORKSPACE_ROOT}/my-lib/registry/index.md" "# registry

Personal manifests.
"

# AGENTS.md with symlinks
ensure_file "${WORKSPACE_ROOT}/my-lib/AGENTS.md" "---
template: agent-automation-user
version: 1.0.0
last_updated: $(date +%Y-%m-%d)
maintainer: pvragon
---

# Agent Instructions

> **CONTEXT:** You are operating in **Layer 2** (\`my-lib\`) of the Pvragon AI Workspace.
> **USER:** You are the User's Personal Automation Engine.

This file is mirrored across CLAUDE.md, AGENTS.md, and GEMINI.md so the same instructions load in any AI environment.

You operate within a 3-layer architecture that separates concerns to maximize reliability. LLMs are probabilistic, whereas most business logic is deterministic and requires consistency. This system fixes that mismatch.

## The 3-Layer Architecture

**Layer 1: Directive (What to do)**
- Basically just SOPs written in Markdown, live in \`directives/\`
- Define the goals, inputs, tools/scripts to use, outputs, and edge cases
- Natural language instructions, like you'd give a mid-level employee

**Layer 2: Orchestration (Decision making)**
- This is you. Your job: intelligent routing.
- Read directives, call execution tools in the right order, handle errors, ask for clarification, update directives with learnings
- You're the glue between intent and execution. E.g you don't try scraping websites yourself—you read \`directives/scrape_website.md\` and come up with inputs/outputs and then run \`executions/scrape_single_site.py\`

**Layer 3: Execution (Doing the work)**
- Deterministic Python scripts in \`executions/\`
- Environment variables, api tokens, etc are stored in \`~/ai-workspace/personal/secrets/.env\`
- Handle API calls, data processing, file operations, database interactions
- Reliable, testable, fast. Use scripts instead of manual work. Commented well.

**Why this works:** if you do everything yourself, errors compound. 90% accuracy per step = 59% success over 5 steps. The solution is push complexity into deterministic code. That way you just focus on decision-making.

## Operating Principles

**1. Check for tools first (Local Priority)**
Before writing a script, check for existing capabilities in this specific order:
1.  **Local:** Check \`./executions/\` (Scripts) and \`./skills/\` (Definitions).
2.  **System:** Check \`~/.ai-workspace-manifest.yaml\` to locate team-lib, then check \`team-lib/executions/\` and \`team-lib/skills/\`.
*Tip:* You can also check \`registry/skills.yaml\` and use the manifest to locate team-lib registry.
Only create new scripts (in \`./executions/\`) if no tool or skill currently exists.

**2. Self-anneal when things break**
- Read error message and stack trace
- Fix the script and test it again (unless it uses paid tokens/credits/etc—in which case you check w user first)
- Update the directive with what you learned (API limits, timing, edge cases)
- Example: you hit an API rate limit → you then look into API → find a batch endpoint that would fix → rewrite script to accommodate → test → update directive.

**3. Update directives as you learn**
Directives are living documents. When you discover API constraints, better approaches, common errors, or timing expectations—update the directive. But don't create or overwrite directives without asking unless explicitly told to. Directives are your instruction set and must be preserved (and improved upon over time, not extemporaneously used and then discarded).

## Self-annealing loop

Errors are learning opportunities. When something breaks:
1. Fix it
2. Update the tool
3. Test tool, make sure it works
4. Update directive to include new flow
5. System is now stronger

## File Organization

**Deliverables vs Intermediates:**
- **Deliverables**: Final artifacts that the user can access.
- **Intermediates**: Temporary files needed during processing.

**Directory structure:**
- \`runtime/.tmp\` - All intermediate files (dossiers, scraped data, temp exports). Never commit, always regenerated.
- \`runtime/deliverables\` - All final artifacts (reports, exports, logs, etc).
- \`executions/\` - Python scripts (the deterministic tools).
- \`directives/\` - SOPs in Markdown (the instruction set).
- \`secrets/.env\` - Environment variables and API keys
- \`secrets/credentials.json\`, \`secrets/token.json\` - Google OAuth credentials (required files, in \`.gitignore\`)
- \`personal/\` - Check \`preferences/\` for user context before starting.

**Key principle:** Local files are only for processing (scripts/configs). Deliverables live in \`runtime/deliverables\` or cloud services. Everything in \`runtime/.tmp\` can be deleted and regenerated.

## Summary

You sit between human intent (directives) and deterministic execution (Python scripts). Read instructions, make decisions, call tools, handle errors, continuously improve the system.

Be pragmatic. Be reliable. Self-anneal.
"

# Gitignore for private library
ensure_file "${WORKSPACE_ROOT}/my-lib/.gitignore" "/runtime/
/secrets/
"

# ============================================================================
# PROJECTS
# ============================================================================

ensure_file "${WORKSPACE_ROOT}/projects/index.md" "# projects

## Purpose
Active Development Factory—container for all project repositories (private and team).

## What Belongs Here
- All project repositories (private and team)
- Each project in its own subdirectory
- Projects follow the standard structure: \`src/\`, \`docs/specs/\`, \`docs/context/\`, \`docs/directives/\`

## What Does NOT Belong Here
- Library code (use \`team-lib/\` or \`my-lib/\`)
- Reusable automations (use libraries)

## Project Structure Convention
\`\`\`
<project>/
├── src/                # Source code
├── docs/
│   ├── specs/          # Definition of done
│   ├── context/        # Project context for agents
│   └── directives/     # Project-specific rules
└── README.md
\`\`\`

## Operational Mode
When working in this directory, agents operate in **Engineering Mode**:
- Read \`docs/specs/\` for requirements
- Read \`docs/context/\` for background
- Write source code, run tests
"

# ============================================================================
# _ADMIN (within team-lib)
# ============================================================================

ensure_file "${WORKSPACE_ROOT}/team-lib/_admin/index.md" "# _admin

Administrative scripts for workspace management.

Located within team-lib for version control and team collaboration.
"

# ============================================================================
# ROOT SYMLINKS
# ============================================================================

# Root safety config symlink
if [[ ! -L "${WORKSPACE_ROOT}/CLAUDE.md" && ! -f "${WORKSPACE_ROOT}/CLAUDE.md" ]]; then
    ln -s "team-lib/context/global/template-agent-safety.md" "${WORKSPACE_ROOT}/CLAUDE.md"
    echo "Created symlink: CLAUDE.md -> team-lib/context/global/template-agent-safety.md"
fi

# Registry symlink
if [[ ! -L "${WORKSPACE_ROOT}/workspace.yaml" && ! -f "${WORKSPACE_ROOT}/workspace.yaml" ]]; then
    ln -s "team-lib/registry/workspace.yaml" "${WORKSPACE_ROOT}/workspace.yaml"
    echo "Created symlink: workspace.yaml -> team-lib/registry/workspace.yaml"
fi

# my-lib agent config symlinks
if [[ ! -L "${WORKSPACE_ROOT}/my-lib/CLAUDE.md" && ! -f "${WORKSPACE_ROOT}/my-lib/CLAUDE.md" ]]; then
    ln -s "AGENTS.md" "${WORKSPACE_ROOT}/my-lib/CLAUDE.md"
    echo "Created symlink: my-lib/CLAUDE.md -> AGENTS.md"
fi

if [[ ! -L "${WORKSPACE_ROOT}/my-lib/GEMINI.md" && ! -f "${WORKSPACE_ROOT}/my-lib/GEMINI.md" ]]; then
    ln -s "AGENTS.md" "${WORKSPACE_ROOT}/my-lib/GEMINI.md"
    echo "Created symlink: my-lib/GEMINI.md -> AGENTS.md"
fi

# projects engineering mode symlink
if [[ ! -L "${WORKSPACE_ROOT}/projects/CLAUDE.md" && ! -f "${WORKSPACE_ROOT}/projects/CLAUDE.md" ]]; then
    ln -s "../team-lib/context/global/template-agent-engineering.md" "${WORKSPACE_ROOT}/projects/CLAUDE.md"
    echo "Created symlink: projects/CLAUDE.md -> template-agent-engineering.md"
fi

# ============================================================================
# MAKE SCRIPTS EXECUTABLE
# ============================================================================

chmod +x "${WORKSPACE_ROOT}/team-lib/_admin/bootstrap_local.sh" 2>/dev/null || true

# ============================================================================
# GENERATE WORKSPACE MANIFEST
# ============================================================================

generate_manifest() {
    local manifest_file="$1"
    local workspace_root="$2"
    local username=$(whoami)
    
    cat > "$manifest_file" << EOF
# workspace-manifest.yaml
# Generated by: bootstrap_local.sh on $(date)
# Location: $manifest_file
# Purpose: Single source of truth for workspace paths across all machines

version: "1.0"
generated_at: "$(date -u +%Y-%m-%dT%H:%M:%SZ)"
workspace_layout: "multi-root"
workspace_root: $workspace_root

roots:
  personal:
    path: $workspace_root/personal
    role: user-local
    description: "Private human workspace - notes, secrets, preferences"
    is_git_repo: false
    is_gitignored: true
    key_subdirs:
      notes: notes/
      scratch: scratch/
      preferences: preferences/
      secrets: secrets/
    
  team_lib:
    path: $workspace_root/team-lib
    role: shared-sop
    description: "Shared team library - SOPs, directives, templates"
    is_git_repo: true
    github_repo: Pvragon/pvragon-ai-library
    is_gitignored: false
    key_subdirs:
      registry: registry/
      directives: directives/
      skills: skills/
      personas: personas/
      context_source: context/
      executions: executions/
      harnesses: harnesses/
      admin: _admin/
    
  my_lib:
    path: $workspace_root/my-lib
    role: user-directives
    description: "Personal overlay library - user directives & scripts"
    is_git_repo: true
    github_repo: jkhereford/private-ai-library
    is_gitignored: false
    key_subdirs:
      archive: archive/
      backlog: backlog/
      registry: registry/
      directives: directives/
      skills: skills/
      personas: personas/
      context_source: context/
      executions: executions/
      harnesses: harnesses/
      runtime: runtime/
    
  projects:
    path: $workspace_root/projects
    role: active-repos
    description: "Active development - all project repositories"
    is_git_repo: false
    contains_git_repos: true
    key_subdirs: {}

context_layers:
  - team_lib
  - my_lib
  - personal

project_structure:
  src: "Source code"
  docs: "Documentation"
  docs/specs: "Requirements and definition of done"
  docs/context: "Project context for agents"
  docs/directives: "Project-specific rules and workflows"
  README.md: "Project overview"
EOF
    echo "Created manifest: $manifest_file"
}

generate_code_workspace() {
    local workspace_file="$1"
    local workspace_root="$2"

    cat > "$workspace_file" << EOF
{
	"folders": [
		{
			"name": "1. Team Library (Shared)",
			"path": "team-lib"
		},
		{
			"name": "2. My Library (Private)",
			"path": "my-lib"
		},
		{
			"name": "3. Projects (Workbench)",
			"path": "projects"
		},
		{
			"name": "0. Personal (Local)",
			"path": "personal"
		}
	],
	"settings": {
		"files.exclude": {
			"**/.git": true,
			"**/.DS_Store": true
		}
	}
}
EOF
    echo "Created workspace file: $workspace_file"
}

echo ""
echo "=== Generating workspace manifest ==="
generate_manifest "$MANIFEST_PATH" "$WORKSPACE_ROOT"

echo ""
echo "=== Generating VS Code workspace ==="
generate_code_workspace "${WORKSPACE_ROOT}/pvragon.code-workspace" "${WORKSPACE_ROOT}"

# ============================================================================
# SET ENVIRONMENT VARIABLE
# ============================================================================

echo ""
echo "=== Setting up environment variable ==="
echo "Add this to your shell profile (~/.bashrc, ~/.zshrc, etc):"
echo "  export WORKSPACE_MANIFEST_PATH=${MANIFEST_PATH}"
echo ""

echo ""
echo "=== Bootstrap complete! ==="
echo "Workspace created at: ${WORKSPACE_ROOT}"
echo "Manifest created at: ${MANIFEST_PATH}"
echo "VS Code Workspace: ${WORKSPACE_ROOT}/pvragon.code-workspace"
echo ""
echo "Structure (Functional Topology):"
echo "  personal/         - Human workspace"
echo "  team-lib/         - Team shared library (includes _admin/)"
echo "  my-lib/           - Personal overlay (with local runtime)"
echo "  projects/         - Project repos"
echo ""
echo "To view the structure, run:"
echo "  tree -L 2 ${WORKSPACE_ROOT}"
echo ""
echo "To reload your environment:"
echo "  source ~/.bashrc  # or ~/.zshrc"
